#!/bin/bash

# Set the file name for the private key
private_key="school"

# Set the number of bits for the RSA key
key_bits=4096

# Set the passphrase for the private key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $key_bits -C "" -N "$passphrase" -f "$private_key"

# Output success message
echo "RSA key pair generated successfully."
